export const IMPORT_MEAL_REQUEST = "IMPORT_MEAL_REQUEST"

export const IMPORT_MEAL_SUCCESS = "IMPORT_MEAL_SUCCESS"

export const IMPORT_MEAL_FAIL = "IMPORT_MEAL_FAIL"

export const CREATE_MEAL_REQUEST = "CREATE_MEAL_REQUEST"

export const CREATE_MEAL_SUCCESS = "CREATE_MEAL_SUCCESS"

export const CREATE_MEAL_FAIL = "CREATE_MEAL_FAIL"

export const SELECT_MEAL_REQUEST = "SELECT_MEAL_REQUEST"

export const SELECT_MEAL_SUCCESS = "SELECT_MEAL_SUCCESS"

export const SELECT_MEAL_FAIL = "SELECT_MEAL_FAIL"